# Generated by Django 4.2.3 on 2023-11-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("query_clause_identifier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryClauseId",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("taskId", models.IntegerField(blank=True, db_index=True, null=True)),
                ("pageId", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "bbox",
                    models.JSONField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("width", models.IntegerField(blank=True, db_index=True, null=True)),
                ("height", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "manualContent",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TermExtract",
        ),
    ]
