# Generated by Django 4.2.3 on 2023-11-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doc_process", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docprocess",
            name="convertTo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="LibreOffice converter is used. It only supports file conversion from .doc to .pdf, .html, .txt, input value must be one of the following: html, pdf, txt, docx",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="docprocess",
            name="createUser",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="username of task creator",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="docprocess",
            name="fileName",
            field=models.CharField(
                db_index=True,
                help_text="the filename of document to be converted",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="docprocess",
            name="filePath",
            field=models.CharField(
                db_index=True,
                help_text="the absolute file path of document to be converted",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="docprocess",
            name="fileType",
            field=models.CharField(
                db_index=True,
                help_text="document type, either FA for facility agreement or TS for term sheet",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="docprocess",
            name="id",
            field=models.IntegerField(
                help_text="document ID (created automatically when file uploaded)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="docprocess",
            name="outputFolder",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="the desired output folder path",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="docprocess",
            name="updateUser",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="username of task updater",
                max_length=255,
                null=True,
            ),
        ),
    ]
